[WIP] more refining of headphones installer (boiler plate)

diff --git a/packages/package/install/installpackage-headphones b/packages/package/install/installpackage-headphones
--- a/packages/package/install/installpackage-headphones
+++ b/packages/package/install/installpackage-headphones
@@ -36,7 +36,7 @@ APPTITLE='Headphones'
 APPDEPS='git-core python python-cheetah python-pyasn1'
 APPGIT='https://github.com/rembo10/headphones.git'
 APPDPORT='8004'
-APPSETTINGS=$APPPATH'/config.ini'
+APPSETTINGS=$APPPATH'/headphones.ini'
 PORTSEARCH='http_port = '
 USERSEARCH='http_username = '
 PASSSEARCH='http_password = '
@@ -85,14 +85,14 @@ echo $APPSHORTNAMEU"_USER="$USERNAME >> $DEFAULTFILE
 
 
 sudo mv $DEFAULTFILE "/etc/default/"$APPNAME || { echo 'Could not move '$APPTITLE' default file.' ; exit 1; }
-cp ${local_setup}templates/sysd/headphones.template /etc/systemd/system/headphones.service
-sed -i "s/USER/${USERNAME}/g" /etc/systemd/system/headphones.service
-systemctl enable headphones >/dev/null 2>&1
-systemctl start headphones >/dev/null 2>&1
-systemctl stop headphones >/dev/null 2>&1
+cp ${local_setup}templates/sysd/$APPNAME.template /etc/systemd/system/$APPNAME.service
+sed -i "s/USER/${USERNAME}/g" /etc/systemd/system/$APPNAME.service
+systemctl enable $APPNAME >/dev/null 2>&1
+systemctl start $APPNAME >/dev/null 2>&1
+systemctl stop $APPNAME >/dev/null 2>&1
 #/etc/init.d/$APPNAME start >/dev/null 2>&1
 #/etc/init.d/$APPNAME stop >/dev/null 2>&1
-#sudo cp $APPPATH/init-scripts/init.ubuntu /etc/init.d/headphones || { echo $RED'Creating init file failed.'$ENDCOLOR ; exit 1; }
+#sudo cp $APPPATH/init-scripts/init.ubuntu /etc/init.d/$APPNAME || { echo $RED'Creating init file failed.'$ENDCOLOR ; exit 1; }
 
 cat > /etc/apache2/sites-enabled/$APPNAME.conf <<EOF
 <Location /$APPNAME>
@@ -101,7 +101,7 @@ ProxyPassReverse http://localhost:$APPDPORT/$APPNAME
 AuthType Digest
 AuthName "rutorrent"
 AuthUserFile '/etc/htpasswd'
-Require user ${MASTER}
+Require user $USERNAME
 </Location>
 EOF
 
@@ -109,20 +109,20 @@ echo
 sleep 1
 echo -e "Enabling $APPTITLE Autostart at Boot ... " >>"${OUTTO}" 2>&1;
 echo -e $YELLOW'--->Enabling '$APPTITLE' Autostart at Boot...'$ENDCOLOR
-sudo chown $USERNAME:$USERNAME /etc/init.d/$APPNAME
-sudo chmod +x /etc/init.d/$APPNAME
+sudo chown $USERNAME:$USERNAME /etc/systemd/system/$APPNAME.service
+sudo chmod +x /etc/systemd/system/$APPNAME.service
 sudo update-rc.d $APPNAME defaults
 
 echo
 sleep 1
 echo -e "Starting $APPTITLE ... " >>"${OUTTO}" 2>&1;
 echo -e $YELLOW'--->Starting '$APPTITLE$ENDCOLOR
-/etc/init.d/$APPNAME start >/dev/null 2>&1
-/etc/init.d/$APPNAME stop >/dev/null 2>&1
+systemctl start $APPNAME >/dev/null 2>&1
+systemctl stop $APPNAME >/dev/null 2>&1
 
 sudo sed -i 's@http_host = localhost@http_host = 0.0.0.0@g' $APPSETTINGS  || { echo -e $RED'Modifying http_host in config file failed.'$ENDCOLOR; exit 1; }
 
-/etc/init.d/$APPNAME start
+systemctl start $APPNAME
 
 touch /install/.$APPNAME.lock
 echo
